.\"* libvdeplug: a network namespace as a user library
.\" Copyright (C) 2018 Michele Nalli. University of Bologna. <michele.nalli@studio.unibo.it>
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public
.\" License as published by the Free Software Foundation; either
.\" version 2.1 of the License, or (at your option) any later version.
.\"
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

.TH LIBVDEPLUG_AGNO 1 "April 30, 2017" "Virtual Distributed Ethernet"

.SH NAME
libvdeplug_agno \- vdeplug module: encryption plugin for LAN networks.
.SH SYNOPSIS
libvdeplug_agno.so
.SH DESCRIPTION
This is a libvdeplug cryptographic module that implements agnostic encryption
over layer 2.
Agnostic encryption is an encryption method that doesn't need information about
the lenght of the ip packet.

This module of libvdeplug4 can be used in any program supporting vde, like
\fBvde_plug\fR, \fBkvm\fR, \fBqemu\fR, \fBuser-mode-linux\fR and \fBvirtualbox\fR.

The vde_plug_url syntax of this module is the following:
.RS
.B agno:///path/to/config/file{\fIvde nested url\fP}
.br
.RE

\fI/path/to/config/file\fR, if present, must be an absolute path or a path relative
to the user's home (~/example/path).
If omitted the path of the keyfile is ~/.agno_config.

The configuration file must have the following structure:
.br
id
.br
absolute/path/to/public/keyfile
.br
absolute/path/to/private/key
.br

NOTE: The public key found in the public keyfile after the id and the private key
specified must be a pair of 2048-bits RSA keys and must be readable to the current
user.

A pair of RSA keys can be generated with openssl using the following command:
.RS
.B openssl genrsa -out private.pem 2048
.br
.RE

private.pem will contain both the private and the public key in plaintext.
To print out the relative public key we could do:
.RS
.B openssl rsa -in private.pem -outform PEM -pubout
.br
.RE

The public keys file we're going to use has the following structure:
.br
id_1:
.br
-----BEGIN PUBLIC KEY-----
.br
public key id_1
.br
-----END PUBLIC KEY-----
.br
id_2:
.br
-----BEGIN PUBLIC KEY-----
.br
public key id_2
.br
-----END PUBLIC KEY-----
.br

The management of the security of the keys is left to the user.
Keyfiles (both private and public) should only be editable by trusted users.

.SH OPTIONS
.TP
\fBethtype=\fR\fITYPE
define the type of the Ethernet frame of the encrypted packet.
\fITYPE\fR can be the number that specifies the bytes of the type.

\fITYPE\fR can be also be a string value such as copy, ipv4, ipv6, rand.
.RS
.B \fIcopy\fR: same type of the non-encrypted packet.
.br
.B \fIipv4\fR: ipv4 type (0x0800).
.br
.B \fIipv6\fR: ipv6 type (0x86dd).
.br
.B \fIrand\fR: random number as type. The random number will be generated for
every Ethernet packet sent.
.RE
.SH EXAMPLES
.B vde_plug agno://{vde:///tmp/myswitch}
.br
agno uses the key stored in the default keyfile (~/.vde_agno_key) location to
encrypt the traffic sent to the switch. The Ethernet frames will have agno
specific type (0xa6de) as type.
.br
.B vde_plug agno:///tmp/my_keyfile[ethtype=copy]{vde:///tmp/myswitch}
.br
agno uses the key stored in file /tmp/my_keyfile to encrypt the traffic sent to
the switch. The Ethernet frames will have the same type of the non-encrypted packet.
(0xa6de) as type.
.br
.B agno://[ethtype=rand]{vxvde://234.0.0.1}
.br
agno uses the key stored in the default keyfile (~/.vde_agno_key) location to
encrypt the traffic sent to vxvde. Packets sent will have tag.
.SH NOTICE
Virtual Distributed Ethernet is not related in any way with
www.vde.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik"
i.e. the German "Association for Electrical, Electronic & Information
Technologies").
.SH SEE ALSO
\fBvde_plug\fP(1).
.SH BUGS
Bug reports should be addressed to <info@virtualsquare.org>
.SH AUTHOR
Renzo Davoli <renzo@cs.unibo.it>
